name: google_signin_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flutter_html: ^0.11.0
  intl: ^0.16.1
  cached_network_image: ^2.0.0  

  cupertino_icons: ^1.0.0
  video_player:
  url_launcher:
  html:
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6

  # state management
  provider: ^4.3.2+2

  # icon of google
  font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
    - images/  